graph LR
  AppConfigModule-->ConfigHostModule
  AppConfigModule-->ConfigModule
  AppConfigModule-->DatabaseModule
  AppConfigModule-->OpenAiModule
  AppConfigModule-->RedisModule
  AppConfigModule-->ScheduleModule
  AppModule-->AppConfigModule
  AppModule-->ArticlesModule
  AppModule-->ChatModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->DatabaseModule
  AppModule-->OpenAiModule
  AppModule-->RedisModule
  AppModule-->ScheduleModule
  AppModule-->ScraperModule
  AppModule-->SourcesModule
  ArticlesModule-->AppConfigModule
  ArticlesModule-->ConfigHostModule
  ArticlesModule-->ConfigModule
  ArticlesModule-->DatabaseModule
  ArticlesModule-->OpenAiModule
  ArticlesModule-->RedisModule
  ArticlesModule-->ScheduleModule
  ChatModule-->AppConfigModule
  ChatModule-->ConfigHostModule
  ChatModule-->ConfigModule
  ChatModule-->DatabaseModule
  ChatModule-->OpenAiModule
  ChatModule-->RedisModule
  ChatModule-->ScheduleModule
  ConfigHostModule-->AppConfigModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->DatabaseModule
  ConfigHostModule-->OpenAiModule
  ConfigHostModule-->RedisModule
  ConfigHostModule-->ScheduleModule
  ConfigModule-->AppConfigModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->DatabaseModule
  ConfigModule-->OpenAiModule
  ConfigModule-->RedisModule
  ConfigModule-->ScheduleModule
  DatabaseModule-->AppConfigModule
  DatabaseModule-->ConfigHostModule
  DatabaseModule-->ConfigModule
  DatabaseModule-->OpenAiModule
  DatabaseModule-->RedisModule
  DatabaseModule-->ScheduleModule
  DiscoveryModule-->AppConfigModule
  DiscoveryModule-->ConfigHostModule
  DiscoveryModule-->ConfigModule
  DiscoveryModule-->DatabaseModule
  DiscoveryModule-->OpenAiModule
  DiscoveryModule-->RedisModule
  DiscoveryModule-->ScheduleModule
  OpenAiModule-->AppConfigModule
  OpenAiModule-->ConfigHostModule
  OpenAiModule-->ConfigModule
  OpenAiModule-->DatabaseModule
  OpenAiModule-->RedisModule
  OpenAiModule-->ScheduleModule
  RedisModule-->AppConfigModule
  RedisModule-->ConfigHostModule
  RedisModule-->ConfigModule
  RedisModule-->DatabaseModule
  RedisModule-->OpenAiModule
  RedisModule-->ScheduleModule
  RootTestModule-->AppConfigModule
  RootTestModule-->AppModule
  RootTestModule-->ConfigHostModule
  RootTestModule-->ConfigModule
  RootTestModule-->DatabaseModule
  RootTestModule-->OpenAiModule
  RootTestModule-->RedisModule
  RootTestModule-->ScheduleModule
  ScheduleModule-->AppConfigModule
  ScheduleModule-->ConfigHostModule
  ScheduleModule-->ConfigModule
  ScheduleModule-->DatabaseModule
  ScheduleModule-->DiscoveryModule
  ScheduleModule-->OpenAiModule
  ScheduleModule-->RedisModule
  ScraperModule-->AppConfigModule
  ScraperModule-->ConfigHostModule
  ScraperModule-->ConfigModule
  ScraperModule-->DatabaseModule
  ScraperModule-->OpenAiModule
  ScraperModule-->RedisModule
  ScraperModule-->ScheduleModule
  ScraperModule-->TransformerModule
  SourcesModule-->AppConfigModule
  SourcesModule-->ConfigHostModule
  SourcesModule-->ConfigModule
  SourcesModule-->DatabaseModule
  SourcesModule-->OpenAiModule
  SourcesModule-->RedisModule
  SourcesModule-->ScheduleModule
  TransformerModule-->AppConfigModule
  TransformerModule-->ConfigHostModule
  TransformerModule-->ConfigModule
  TransformerModule-->DatabaseModule
  TransformerModule-->OpenAiModule
  TransformerModule-->RedisModule
  TransformerModule-->ScheduleModule
